[package]
name = "place"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8", features = ["ws"] }
redis = { version = "0.28.2", features = ["tokio-comp"] }
rust-embed = "8.5.0"
scylla = "0.15.1"
tokio = { version = "1.43", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
futures-util = "0.3.31"
serde = { version = "1.0.217", features = ["derive"] }
bincode = "1.3.3"
log = "0.4.25"