version: "1"

volumes:
  scylla-data:
    driver: local

services:
  scylla:
    image: scylladb/scylla:4.6.0
    environment:
      - SCYLLA_CLUSTER_NAME=ScyllaCluster
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_SEEDS=scylla
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9142:9142"
    volumes:
      - scylla-data:/var/server/scylla
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"