version: "1"

services:
  scylla-test:
    image: scylladb/scylla:4.6.0
    environment:
      - SCYLLA_CLUSTER_NAME=ScyllaCluster
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_SEEDS=scylla
    ports:
      - "9043:9042"  # CQL port
      - "8000:7000"  # Internode communication
      - "8001:7001"  # TLS internode communication
      - "8199:7199"  # JMX port
      - "10142:9142"  # Scylla monitoring port
  valkey-test:
    image: valkey/valkey
    ports:
      - "6380:6379"